version = "1.1.14"

[class]
spotify = ""
chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default = ""
darktable = ""
slack = ""
udiskie = ""
org-ksnip-ksnip = ""
songrec = ""
org-pwmt-zathura = ""
virt-manager = ""
vimiv = ""
code-oss = ""
kak = ""
fontforge = ""
element = ""
libreoffice-writer = ""
sun-awt-x11-xframepeer = ""
DEFAULT = ""
dmenu-emoji = ""
vlc = ""
bleachbit = ""
zoom = ""
shopping = ""
wlfreerdp = "󰀄"
swappy = ""
calibre-gui = ""
qutepreview = ""
neomutt = ""
cssh = ""
nemo = ""
paperwork = ""
nm-connection-editor = ""
scli = ""
"dmenu-pass generator" = ""
libreoffice-impress = ""
gsimplecalc = ""
libreoffice-calc = ""
chromium = ""
pavucontrol = ""
"(?i)waydroid.*" = "droid"
dmenu-pass = ""
"(?i)alacritty" = ""
telegramdesktop = ""
"Gimp-2.10" = ""
libreoffice-startcenter = ""
wayvnc = "󰀄"
krita = ""
taskwarrior-tui = ""
whatsapp-nativefier-d52542 = ""
wireshark-gtk = ""
streamlink-twitch-gui = ""
whatsapp-desktop = ""
org-telegram-desktop = ""
personal = ""
rapid-photo-downloader = ""
kicad = ""
org-qutebrowser-qutebrowser = ""
mpv = ""
".*transmission.*" = ""
vncviewer = ""
xplr = ""
remote-viewer = ""
plexamp = ""
sandboxed-tor-browser = ""
snappergui = ""
"(?i)firefox" = "<span color='orange'> </span>"
discord = ""
duolingo = ""
steam = ""
wire = "󰁀"
dmenu-browser = ""
obsidian = ""
burp-startburp = ""
Signal = ""
dmenu-clipboard = ""
jetbrains-studio = ""
work = ""
qalculate-gtk = ""
molotov = ""
"(?i)kitty" = ""
gcr-prompter = ""

[class_active]
"(?i)firefox" = "<span color='orange'> {class}</span>"
DEFAULT = "{icon}"

[initial_class]
DEFAULT = " {class}: {title}"

[initial_class_active]

[workspaces_name]
1 = "one"
6 = "six"
2 = "two"
5 = "five"
3 = "three"
8 = "eight"
9 = "nine"
7 = "seven"
10 = "ten"
0 = "zero"
4 = "four"

[title_in_class."(?i)foot"]
"emerge: (.+?/.+?)-.*" = "{match1}"

[title_in_class."(firefox|chrom.*)"]
"(?i)youtube" = "ꟳ"
"(?i)twitch" = "ꟳ"

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class.kitty]
zsh = "Zsh"

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"" = "^$"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
workspace = "<b><span color='#458588'>{id}-{name}:</span></b>{delim}{clients}"
workspace_empty = "<b><span color='white'>{id}-{name}:</span></b>{delim}{clients}"
client = "{icon}{delim}"
client_fullscreen = "[{icon}]{delim}"
client_active = "<span color='#458588'>{icon}</span>"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
