#!/bin/sh

# Created By: Javier Pacheco - jpacheco@cock.li
# Created On: 12/04/24
# Project: Update and sync dotfiles repo from local to remote


git_push() {
    git add .
    git commit -m "$(date "+%A %F %I:%M:%S")"
    git push
}

git_push

