#!/bin/sh

# Created By: Javier Pacheco - jpacheco@cock.li
# Created On: 12/04/24
# Project: Update and sync dotfiles repo from local to remote


git_push() {
    git add .
    echo "Commit message: "
    read commit
    git commit -m "$commit"
    git push
}

git_push

