#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Export all vars
set -o allexport

# Adds `~/.local/bin` to $PATH
PATH="$PATH:${$(find ~/.local/bin -type d,l -printf %p:)%%:}"
PATH=$PATH:/home/javier/.local/share/nvim/mason/bin
PATH=$PATH:/sbin

unsetopt PROMPT_SP

# Default programs:
EDITOR="nvim"
TERMINAL="kitty -1"
# BROWSER="firefox"
BROWSER="qutebrowser"

# ~/ Clean-up:
XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_BIN_HOME=$HOME/.local/bin/scripts
XDG_CACHE_HOME="$HOME/.cache"
XDG_RUNTIME_DIR=$(mktemp -d /tmp/$(id -u)-runtime-dir.XXX)
XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
# GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
XCURSOR_THEME="Bibata-Modern-Classic"
LESSHISTFILE="-"
WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
TMUX_TMPDIR="$XDG_RUNTIME_DIR"
ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"
BAT_THEME="gruvbox-dark"
GI_TYPELIB_PATH="/run/current-system/sw/lib/girepository-1.0";

# Other program settings:
DICS="/usr/share/stardict/dic/"
# SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
DOAS_ASKPASS="$HOME/.local/bin/scripts/tofi-pass.sh"
# FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:-1,fg+:#d0d0d0,bg:-1,bg+:#282828
  --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00
  --color=prompt:#458588,spinner:#af5fff,pointer:#af5fff,header:#87afaf
  --color=gutter:-1,border:#262626,label:#aeaeae,query:#d9d9d9
  --border="bold" --border-label="" --preview-window="border-bold" --prompt="❯❯ "
  --marker="*" --pointer="❯" --separator="─" --scrollbar="│"
  --layout="reverse-list" --info="right" --height 40%'
LESS=-R
LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
LESS_TERMCAP_me="$(printf '%b' '[0m')"
LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
LESS_TERMCAP_se="$(printf '%b' '[0m')"
LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
LESS_TERMCAP_ue="$(printf '%b' '[0m')"
LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
_JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &

# Start wayland server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && exec Hyprland
xrdb ~/.config/.Xdefaults
# [ "$(tty)" = "/dev/tty1" ] && exec sway
