;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from jp-abbrev.el

(register-definition-prefixes "jp-abbrev" '("jp-abbrev-"))


;;; Generated autoloads from jp-coach.el

(autoload 'jp-coach-jitsi-link "jp-coach" "\
Insert Jitsi link for NAME person.

(fn NAME)" t)
(autoload 'jp-coach-done-sessions-with-person "jp-coach" "\
Produce buffer with time table for a given student." t)
(function-put 'jp-coach-done-sessions-with-person 'interactive-only 't)
(register-definition-prefixes "jp-coach" '("jp-coach-"))


;;; Generated autoloads from jp-comment.el

(autoload 'jp-comment "jp-comment" "\
Comment N lines, defaulting to the current one.
When the region is active, comment its lines instead.

(fn N)" t)
(autoload 'jp-comment-timestamp-keyword "jp-comment" "\
Add timestamped comment with KEYWORD.

When called interactively, the list of possible keywords is that
of `jp-comment-keywords', though it is possible to input
arbitrary text.

If point is at the beginning of the line or if line is empty (no
characters at all or just indentation), the comment is started
there in accordance with `comment-style'.  Any existing text
after the point will be pushed to a new line and will not be
turned into a comment.

If point is anywhere else on the line and the line is not empty,
the comment is appended to the line with `comment-indent'.

The comment is always formatted as DELIMITER KEYWORD DATE:, with
the date format being controlled by the variable
`jp-comment-timestamp-format-concise'.  DELIMITER is the value
of `comment-start', as defined by the current major mode.

With optional VERBOSE argument (such as a prefix argument), use
an alternative date format, as specified by
`jp-comment-timestamp-format-verbose'.

(fn KEYWORD &optional VERBOSE)" t)
(register-definition-prefixes "jp-comment" '("jp-comment-"))


;;; Generated autoloads from jp-common.el

(autoload 'jp-common-number-even-p "jp-common" "\
Test if N is an even number.

(fn N)")
(autoload 'jp-common-number-integer-p "jp-common" "\
Test if N is an integer.

(fn N)")
(autoload 'jp-common-number-integer-positive-p "jp-common" "\
Test if N is a positive integer.

(fn N)")
(autoload 'jp-common-number-negative "jp-common" "\
Make N negative.

(fn N)")
(autoload 'jp-common-reverse-percentage "jp-common" "\
Determine the original value of NUMBER given PERCENT.

CHANGE-P should specify the increase or decrease.  For simplicity,
nil means decrease while non-nil stands for an increase.

NUMBER must satisfy `numberp', while PERCENT must be `natnump'.

(fn NUMBER PERCENT CHANGE-P)")
(autoload 'jp-common-percentage-change "jp-common" "\
Find percentage change between N-ORIGINAL and N-FINAL numbers.

When the percentage is not an integer, it is rounded to 4
floating points: 16.666666666666664 => 16.667.

(fn N-ORIGINAL N-FINAL)")
(autoload 'jp-common-seconds-to-minutes-or-hours "jp-common" "\
Convert SECONDS to either minutes or hours, depending on the value.

(fn SECONDS)")
(autoload 'jp-common-fahrenheit-to-celsius "jp-common" "\
Convert Fahrenheit DEGREE to Celsius.

(fn DEGREE)" t)
(autoload 'jp-common-celsius-to-fahrenheit "jp-common" "\
Convert Celsius DEGREE to Fahrenheit.

(fn DEGREE)" t)
(autoload 'jp-common-rotate-list-of-symbol "jp-common" "\
Rotate list value of SYMBOL by moving its car to the end.
Return the first element before performing the rotation.

This means that if `sample-list' has an initial value of `(one
two three)', this function will first return `one' and update the
value of `sample-list' to `(two three one)'.  Subsequent calls
will continue rotating accordingly.

(fn SYMBOL)")
(autoload 'jp-common-empty-buffer-p "jp-common" "\
Test whether the buffer is empty.")
(autoload 'jp-common-minor-modes-active "jp-common" "\
Return list of active minor modes for the current buffer.")
(autoload 'jp-common-truncate-lines-silently "jp-common" "\
Toggle line truncation without printing messages.")
(autoload 'jp-common-clear-minibuffer-message "jp-common" "\
Print an empty message to clear the echo area.
Use this as advice :after a noisy function.

(fn &rest _)")
(autoload 'jp-common-disable-hl-line "jp-common" "\
Disable Hl-Line-Mode (for hooks).")
(autoload 'jp-common-window-bounds "jp-common" "\
Return start and end points in the window as a cons cell.")
(autoload 'jp-common-page-p "jp-common" "\
Return non-nil if there is a `page-delimiter' in the buffer.")
(autoload 'jp-common-window-small-p "jp-common" "\
Return non-nil if window is small.
Check if the `window-width' or `window-height' is less than
`split-width-threshold' and `split-height-threshold',
respectively.")
(autoload 'jp-common-three-or-more-windows-p "jp-common" "\
Return non-nil if three or more windows occupy FRAME.
If FRAME is non-nil, inspect the current frame.

(fn &optional FRAME)")
(autoload 'jp-common-read-data "jp-common" "\
Read Elisp data from FILE.

(fn FILE)")
(autoload 'jp-common-completion-category "jp-common" "\
Return completion category.")
(autoload 'jp-common-completion-table "jp-common" "\
Pass appropriate metadata CATEGORY to completion CANDIDATES.

This is intended for bespoke functions that need to pass
completion metadata that can then be parsed by other
tools (e.g. `embark').

(fn CATEGORY CANDIDATES)")
(autoload 'jp-common-completion-table-no-sort "jp-common" "\
Pass appropriate metadata CATEGORY to completion CANDIDATES.
Like `jp-common-completion-table' but also disable sorting.

(fn CATEGORY CANDIDATES)")
(autoload 'jp-common-crm-exclude-selected-p "jp-common" "\
Filter out INPUT from `completing-read-multiple'.
Hide non-destructively the selected entries from the completion
table, thus avoiding the risk of inputting the same match twice.

To be used as the PREDICATE of `completing-read-multiple'.

(fn INPUT)")
(autoload 'jp-common-auth-get-field "jp-common" "\
Find PROP in `auth-sources' for HOST entry.

(fn HOST PROP)")
(autoload 'jp-common-parse-file-as-list "jp-common" "\
Return the contents of FILE as a list of strings.
Strings are split at newline characters and are then trimmed for
negative space.

Use this function to provide a list of candidates for
completion (per `completing-read').

(fn FILE)")
(autoload 'jp-common-contrast "jp-common" "\
Measure WCAG contrast ratio between C1 and C2.
C1 and C2 are color values written in hexadecimal RGB.

(fn C1 C2)")
(register-definition-prefixes "jp-common" '("jp-common-"))


;;; Generated autoloads from jp-dired.el

(autoload 'jp-dired-search-flat-list "jp-dired" "\
Return a Dired buffer for files matching REGEXP.
Perform the search recursively from the current directory.

(fn REGEXP)" t)
(autoload 'jp-dired-limit-regexp "jp-dired" "\
Limit Dired to keep files matching REGEXP.

With optional OMIT argument as a prefix (\\[universal-argument]),
exclude files matching REGEXP.

Restore the buffer with \\<dired-mode-map>`\\[revert-buffer]'.

(fn REGEXP OMIT)" t)
(autoload 'jp-dired-grep-marked-files "jp-dired" "\
Run `find' with `grep' for REGEXP on marked FILES.

(fn FILES REGEXP)" '(dired-mode))
(autoload 'jp-dired-subdirectory-next "jp-dired" "\
Move to next or optional ARGth Dired subdirectory heading.
For more on such headings, read `dired-maybe-insert-subdir'.

(fn &optional ARG)" t)
(autoload 'jp-dired-subdirectory-previous "jp-dired" "\
Move to previous or optional ARGth Dired subdirectory heading.
For more on such headings, read `dired-maybe-insert-subdir'.

(fn &optional ARG)" t)
(autoload 'jp-dired-remove-inserted-subdirs "jp-dired" "\
Remove all inserted Dired subdirectories." t)
(autoload 'jp-dired-insert-subdir "jp-dired" "\
Generic command to insert subdirectories in Dired buffers.

When items are marked, insert those which are subsirectories of
the current directory.  Ignore regular files.

If no files are active and point is on a subdirectory line,
insert it directly.

If no files are active and point is not on a subdirectory line,
prompt for a subdirectory using completion.

With optional ARG as a single prefix (`\\[universal-argument]')
argument, prompt for command line flags to pass to the underlying
ls program.

With optional ARG as a double prefix argument, remove all
inserted subdirectories.

(fn &optional ARG)" t)
(autoload 'jp-dired-setup-imenu "jp-dired" "\
Configure imenu for the current Dired buffer.
Add this to `dired-mode-hook'.")
(register-definition-prefixes "jp-dired" '("jp-dired-"))


;;; Generated autoloads from jp-ediff.el

(register-definition-prefixes "jp-ediff" '("jp-ediff-"))


;;; Generated autoloads from jp-elisp.el

(autoload 'jp-elisp-eval-and-print-last-sexp "jp-elisp" "\
Evaluate and print expression before point like `eval-print-last-sexp'.
Prepend a comment to the return value.  Also copy the return value to
the `kill-ring' and set the mark to where point was before inserting the
return value." t)
(function-put 'jp-elisp-eval-and-print-last-sexp 'interactive-only 't)
(autoload 'jp-elisp-pp-macroexpand-last-sexp "jp-elisp" "\
Like `pp-macroexpand-last-sexp' but with a generic `display-buffer'.
Now use `display-buffer-alist' like the Lisp gods intended." t)
(function-put 'jp-elisp-pp-macroexpand-last-sexp 'interactive-only 't)
(register-definition-prefixes "jp-elisp" '("jp-elisp-macroexpand-mode"))


;;; Generated autoloads from jp-embark.el

(register-definition-prefixes "jp-embark" '("jp-embark-"))


;;; Generated autoloads from jp-eww.el

(autoload 'jp-eww-open-in-other-window "jp-eww" "\
Use `eww-open-in-new-buffer' in another window." t)
(register-definition-prefixes "jp-eww" '("jp-eww-"))


;;; Generated autoloads from jp-icons.el

(defvar jp-icons-dired-mode nil "\
Non-nil if Jp-Icons-Dired mode is enabled.
See the `jp-icons-dired-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `jp-icons-dired-mode'.")
(custom-autoload 'jp-icons-dired-mode "jp-icons" nil)
(autoload 'jp-icons-dired-mode "jp-icons" "\
Display icons for Dired entries.

This is a global minor mode.  If called interactively, toggle the
`Jp-Icons-Dired mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='jp-icons-dired-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(defvar jp-icons-xref-mode nil "\
Non-nil if Jp-Icons-Xref mode is enabled.
See the `jp-icons-xref-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `jp-icons-xref-mode'.")
(custom-autoload 'jp-icons-xref-mode "jp-icons" nil)
(autoload 'jp-icons-xref-mode "jp-icons" "\
Display icons for Xref headings.

This is a global minor mode.  If called interactively, toggle the
`Jp-Icons-Xref mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='jp-icons-xref-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(defvar jp-icons-buffer-menu-mode nil "\
Non-nil if Jp-Icons-Buffer-Menu mode is enabled.
See the `jp-icons-buffer-menu-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `jp-icons-buffer-menu-mode'.")
(custom-autoload 'jp-icons-buffer-menu-mode "jp-icons" nil)
(autoload 'jp-icons-buffer-menu-mode "jp-icons" "\
Display icons for `Buffer-menu-mode' entries.

This is a global minor mode.  If called interactively, toggle the
`Jp-Icons-Buffer-Menu mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='jp-icons-buffer-menu-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "jp-icons" '("jp-icons"))


;;; Generated autoloads from jp-marginalia.el

(register-definition-prefixes "jp-marginalia" '("jp-marginalia-"))


;;; Generated autoloads from jp-minibuffer.el

(defvar jp-minibuffer-missing-categories-mode nil "\
Non-nil if Jp-Minibuffer-Missing-Categories mode is enabled.
See the `jp-minibuffer-missing-categories-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `jp-minibuffer-missing-categories-mode'.")
(custom-autoload 'jp-minibuffer-missing-categories-mode "jp-minibuffer" nil)
(autoload 'jp-minibuffer-missing-categories-mode "jp-minibuffer" "\
When enabled, add missing compleiton categories to relevant prompts.

This is a global minor mode.  If called interactively, toggle the
`Jp-Minibuffer-Missing-Categories mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='jp-minibuffer-missing-categories-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(defvar jp-minibuffer-completions-mode nil "\
Non-nil if Jp-Minibuffer-Completions mode is enabled.
See the `jp-minibuffer-completions-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `jp-minibuffer-completions-mode'.")
(custom-autoload 'jp-minibuffer-completions-mode "jp-minibuffer" nil)
(autoload 'jp-minibuffer-completions-mode "jp-minibuffer" "\
Tweak the interface of the minibuffer and the *Completions*.

This is a global minor mode.  If called interactively, toggle the
`Jp-Minibuffer-Completions mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='jp-minibuffer-completions-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "jp-minibuffer" '("jp-minibuffer" "minibuffer-completion-help"))


;;; Generated autoloads from jp-modeline.el

(register-definition-prefixes "jp-modeline" '("jp-modeline-"))


;;; Generated autoloads from jp-notmuch.el

(autoload 'jp-notmuch-delete-mail "jp-notmuch" "\
Permanently delete mail marked as `jp-notmuch-delete-mail'.
Prompt for confirmation before carrying out the operation.

Do not attempt to refresh the index.  This will be done upon the
next invocation of 'notmuch new'." t)
(autoload 'jp-notmuch-patch-add-email-control-code "jp-notmuch" "\
Add custom header for SourceHut email controls.
The CONTROL-CODE is among `jp-notmuch-patch-control-codes'.

(fn CONTROL-CODE)" t)
(autoload 'jp-notmuch-ask-sourcehut-control-code "jp-notmuch" "\
Use `jp-notmuch-patch-add-email-control-code' programmatically.
Add this to `notmuch-mua-send-hook'.")
(autoload 'jp-notmuch-stash-sourcehut-link "jp-notmuch" "\
Stash web link to current SourceHut thread.
With optional CURRENT argument, produce a link to the current
message, else use the topmost message (start of the thread).

Note that the topmost message is assumed to hold the id of the
base URL, though this is not necessarily true.

(fn &optional CURRENT)" t)
(autoload 'jp-notmuch-check-valid-sourcehut-email "jp-notmuch" "\
Check if SourceHut address is correct.
Add this to `notmuch-mua-send-hook'.")
(register-definition-prefixes "jp-notmuch" '("jp-notmuch-"))


;;; Generated autoloads from jp-orderless.el

(register-definition-prefixes "jp-orderless" '("jp-orderless-"))


;;; Generated autoloads from jp-org.el

(autoload 'jp-org-select-heading-in-file "jp-org" "\
Move to heading in Org file stored in `org-directory'.
Prompt for file, then for heading inside of that file.

This function can also be used as part of an `org-capture' template to
navigate to a file+heading and then capture something which is inserted
there." t)
(function-put 'jp-org-select-heading-in-file 'interactive-only 't)
(autoload 'jp-org-clock-report-current-subtree-or-file "jp-org" "\
Produce a clock report in a new buffer for the subtree at point.
With optional WHOLE-BUFFER as a non-nil value, operate on the entire file.
When called interactively WHOLE-BUFFER is a prefix argument.

(fn &optional WHOLE-BUFFER)" t)
(autoload 'jp-org-clock-select-heading-and-clock-report "jp-org" "\
Select a heading in a file and do a clock report for it in a new buffer." t)
(autoload 'jp-org-coach-report "jp-org" "\
Produce clock report for coaching with person of NAME.
SINCE is the date (of time 00:00) to count from until now.

(fn NAME SINCE)" t)
(autoload 'jp-org-agenda-format-date-aligned "jp-org" "\
Format a DATE string for display in the daily/weekly agenda.
This function makes sure that dates are aligned for easy reading.

Slightly tweaked version of `org-agenda-format-date-aligned' that
produces dates with a fixed length.

(fn DATE)")
(autoload 'jp-org-ox-html "jp-org" "\
Streamline HTML export." t)
(autoload 'jp-org-ox-texinfo "jp-org" "\
Streamline Info export." t)
(autoload 'jp-org-id-headlines "jp-org" "\
Add missing CUSTOM_ID to all headlines in current file." t)
(autoload 'jp-org-id-headlines-readable "jp-org" "\
Like `jp-org-id-headlines' but with readable IDs.
A readable identifier is one derived from the text of the heading.  In
theory, this may not be unique.

With optional FORCE, update the value even if one exists.

(fn &optional FORCE)" t)
(autoload 'jp-org-id-headline "jp-org" "\
Add missing CUSTOM_ID to headline at point.
With optional prefix argument READABLE get a readable identifier derived
from the heading text instead of a UUID.

(fn &optional READABLE)" t)
(autoload 'jp-org-get-dotemacs-link "jp-org" "\
Get URL to current heading in my dotemacs file." t)
(function-put 'jp-org-get-dotemacs-link 'interactive-only 't)
(register-definition-prefixes "jp-org" '("jp-org-"))


;;; Generated autoloads from jp-pair.el

(autoload 'jp-pair-insert "jp-pair" "\
Insert CHARACTER pair an N number of times around object at point.
CHARACTER is one among `jp-pair-pairs'.  The object at point is either
a symbol or the boundaries of the active region.  N is a numeric prefix
argument, defaulting to 1 if none is provided in interactive use.

(fn CHARACTER N)" t)
(autoload 'jp-pair-insert-directly "jp-pair" "\
Read CHARACTER, find it in `jp-pair-pairs', and insert it outright.
Do not use minibuffer completion like `jp-pair-insert'.

(fn CHARACTER N)" t)
(autoload 'jp-pair-delete "jp-pair" "\
Delete pair following or preceding point.
For Emacs version 28 or higher, the feedback's delay is
controlled by `delete-pair-blink-delay'." t)
(register-definition-prefixes "jp-pair" '("jp-pair-"))


;;; Generated autoloads from jp-prefix.el

(register-definition-prefixes "jp-prefix" '("jp-prefix-"))


;;; Generated autoloads from jp-project.el

(autoload 'jp-project-switch "jp-project" "\
Switch to project DIRECTORY.
If DIRECTORY exists in a frame, select it.  Otherwise switch to
the project in DIRECTORY using `project-dired'.

(fn DIRECTORY)" t)
(autoload 'jp-project-in-tab "jp-project" "\
Switch to project DIRECTORY in a tab.
If a tab is named after the non-directory component of DIRECTORY,
switch to it.  Otherwise, create a new tab and name it after the
non-directory component of DIRECTORY.

Use this as an alternative to `project-switch-project'.

(fn DIRECTORY)" t)
(autoload 'jp-project-maybe-in-tab "jp-project" "\
Switch to project depending on `beframe-mode'.
When the mode is enabled (the expected behaviour), use the command
`jp-project-switch'.  Otherwise, do `jp-project-in-tab'." t)
(register-definition-prefixes "jp-project" '("jp-project-"))


;;; Generated autoloads from jp-register.el

(autoload 'jp-simple-file-to-register "jp-register" "\
Store current location of file's point in REGISTER.

(fn REGISTER)" t)
(cl-defmethod register-val-jump-to ((val vector) delete) "\
Handle how to jump to a location register.
This is like the default, but does not ask to visit a file: it does it
outright." (cond ((eq (aref val 0) 'file-with-point) (find-file (aref val 1)) (goto-char (aref val 2)) (run-hooks 'jp-simple-file-to-register-jump-hook)) (t (cl-call-next-method val delete))))
(autoload 'jp-register-add-dwim "jp-register" "\
Do-What-I-Mean with REGISTER.
If the region is active, call `copy-to-register'.

If the optional prefix argument NUMBER is non-nil, then call
`number-to-register'.

If there are more than two windows or there are more than one
`tab-bar-mode' tabs, then do `frameset-to-register'.

Otherwise, use `jp-simple-file-to-register'.

Also see `jp-register-use-dwim'.

(fn REGISTER &optional NUMBER)" t)
(autoload 'jp-register-use-dwim "jp-register" "\
Use the REGISTER, jumping or inserting it, depending on its ocntents.

(fn REGISTER)" t)
(autoload 'jp-register-persist-mode "jp-register" "\
When enabled save `register-alist' to `jp-register-save-file' when a change occurs.

This is a minor mode.  If called interactively, toggle the
`Jp-Register-Persist mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `jp-register-persist-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "jp-register" '("jp-"))


;;; Generated autoloads from jp-scratch.el

(autoload 'jp-scratch-buffer "jp-scratch" "\
Produce a scratch buffer matching the current major mode.

With optional ARG as a prefix argument (\\[universal-argument]),
use `jp-scratch-default-mode'.

With ARG as a double prefix argument, prompt for a major mode
with completion.  Candidates are derivatives of `text-mode' or
`prog-mode'.

If region is active, copy its contents to the new scratch
buffer.

Buffers are named as *MAJOR-MODE scratch*.  If one already exists
for the given MAJOR-MODE, any text is appended to it.

(fn &optional ARG)" t)
(register-definition-prefixes "jp-scratch" '("jp-scratch-"))


;;; Generated autoloads from jp-search.el

(autoload 'jp-search-isearch-other-end "jp-search" "\
End current search in the opposite side of the match.
Particularly useful when the match does not fall within the
confines of word boundaries (e.g. multiple words)." t)
(autoload 'jp-search-isearch-abort-dwim "jp-search" "\
Delete failed `isearch' input, single char, or cancel search.

This is a modified variant of `isearch-abort' that allows us to
perform the following, based on the specifics of the case: (i)
delete the entirety of a non-matching part, when present; (ii)
delete a single character, when possible; (iii) exit current
search if no character is present and go back to point where the
search started." t)
(autoload 'jp-search-isearch-repeat-forward "jp-search" "\
Move forward, keeping point at the beginning of the match.
Optionally move to ARGth match in the given direction.

(fn &optional ARG)" t)
(autoload 'jp-search-isearch-repeat-backward "jp-search" "\
Move backward, keeping point at the beginning of the match.
Optionally move to ARGth match in the given direction.

(fn &optional ARG)" t)
(autoload 'jp-search-occur-urls "jp-search" "\
Produce buttonised list of all URLs in the current buffer." t)
(autoload 'jp-search-occur-browse-url "jp-search" "\
Point browser at a URL in the buffer using completion.
Which web browser to use depends on the value of the variable
`browse-url-browser-function'.

Also see `jp-search-occur-urls'." t)
(autoload 'jp-search-occur-outline "jp-search" "\
Produce buffer outline from `jp-search-outline-regexp-alist'.

With optional prefix ARG (\\[universal-argument]), prompt for a
preset among the entries in `jp-search-outline-regexp-alist'.

ARG may also be a string (or regular expression) when called from
Lisp.

(fn &optional ARG)" t)
(autoload 'jp-search-occur-todo-keywords "jp-search" "\
Produce Occur buffer with `jp-search-todo-keywords'.
With optional numeric prefix argument for CONTEXT, show as many
lines before and after each match.

When called from Lisp CONTEXT must satisfy `natnump'.  A faulty
value is read as 0.

Also see `jp-search-grep-todo-keywords'.

(fn &optional CONTEXT)" t)
(autoload 'jp-search-outline "jp-search" "\
Go to the line of the given outline using completion." t)
(autoload 'jp-search-grep "jp-search" "\
Run grep for REGEXP.
Search in the current directory using `lgrep'.  With optional
prefix argument (\\[universal-argument]) for RECURSIVE, run a
search starting from the current directory with `rgrep'.

(fn REGEXP &optional RECURSIVE)" t)
(autoload 'jp-search-grep-todo-keywords "jp-search" "\
Use `jp-search-grep' to find `jp-search-todo-keywords'.

With optional prefix ARG use git-grep instead for the entire
repository (runs `jp-search-git-grep-todo-keywords').  If Git
is not available on the system, run `jp-search-grep'
recursively, starting from the current directory.

Also see `jp-search-occur-todo-keywords'.

(fn &optional ARG)" t)
(autoload 'jp-search-git-grep-todo-keywords "jp-search" "\
Use the git-grep mechanism for `jp-search-todo-keywords'." t)
 (autoload 'jp-search-find-grep-buffer "jp-search")
 (autoload 'jp-search-find-grep-files-buffer "jp-search")
 (autoload 'jp-search-find-files-buffer "jp-search")
(register-definition-prefixes "jp-search" '("jp-search-"))


;;; Generated autoloads from jp-shell.el

(autoload 'jp-shell-input-from-history "jp-shell" "\
Insert command from shell input history.
Only account for the history Emacs knows about, ignoring
`comint-input-ring-file-name' (e.g. ~/.bash_history)." t)
(function-put 'jp-shell-input-from-history 'interactive-only 't)
(autoload 'jp-shell-cd "jp-shell" "\
Switch to `jp-shell-cd-directories' using minibuffer completion." t)
(function-put 'jp-shell-cd 'interactive-only 't)
(autoload 'jp-shell-cd-vc-root-dir "jp-shell" "\
Change into the `vc-root-dir'." t)
(autoload 'jp-shell-up-dwim "jp-shell" "\
Return previous ARGth history input or go ARGth lines up.
If point is at the beginning of a shell prompt, return previous
input, otherwise perform buffer motion.

(fn ARG)" t)
(autoload 'jp-shell-down-dwim "jp-shell" "\
Return next ARGth history input or or go ARGth lines down.
If point is at the beginning of a shell prompt, return previous
input, otherwise perform buffer motion.

(fn ARG)" t)
(autoload 'jp-shell "jp-shell" "\
Like `shell' but always start a new shell.
Name the shell buffer after the `default-directory'.  If the name of
that buffer already exists, then reuse it." t)
(register-definition-prefixes "jp-shell" '("jp-shell-"))


;;; Generated autoloads from jp-simple.el

(autoload 'jp-simple-describe-at-point "jp-simple" "\
Describe the SYMBOL at point.
If there is no symbol or the symbol at point does not satisfy `symbolp',
prompt for one.

(fn SYMBOL)" t)
(autoload 'jp-simple-indent-dwim "jp-simple" "\
Indent the current defun in `prog-mode' or paragraph in `text-mode'." t)
(autoload 'jp-simple-sudo "jp-simple" "\
Find the current file or directory using `sudo'." t)
(autoload 'jp-simple-mark-sexp "jp-simple" "\
Mark symbolic expression at or near point.
Repeat to extend the region forward to the next symbolic
expression." t)
(autoload 'jp-simple-keyboard-quit-dwim "jp-simple" "\
Do-What-I-Mean behaviour for a general `keyboard-quit'.

The generic `keyboard-quit' does not do the expected thing when
the minibuffer is open.  Whereas we want it to close the
minibuffer, even without explicitly focusing it.

The DWIM behaviour of this command is as follows:

- When the region is active, disable it.

- When a minibuffer is open, but not focused, close the minibuffer.  For
  recursive minibuffers, make sure to only close one level of depth.

- When in a *Completions* or `special-mode' buffer (e.g. *Help* or
  *Messages*), close it.

- When the *Completions* or a `special-mode' buffer is on display but
  not selected, close it.  If there are more than one, close them all.

- In every other case use the regular `keyboard-quit'." t)
(autoload 'jp-simple-delete-window-dwim "jp-simple" "\
Do What I Mean to delete the current THING.
When there is more than one window, THING is a window.
When there are more than one `tab-bar-mode' tabs, THING is a tab.
Else THING is a frame if frames are more than one." t)
(function-put 'jp-simple-delete-window-dwim 'interactive-only 't)
(autoload 'jp-simple-new-line-below "jp-simple" "\
Create N empty lines below the current one.
When called interactively without a prefix numeric argument, N is
1.

(fn N)" t)
(autoload 'jp-simple-new-line-above "jp-simple" "\
Create N empty lines above the current one.
When called interactively without a prefix numeric argument, N is
1.

(fn N)" t)
(autoload 'jp-simple-copy-line "jp-simple" "\
Copy the current line to the `kill-ring'." t)
(autoload 'jp-simple-kill-ring-save "jp-simple" "\
Copy the current region or line.
When the region is active, use `kill-ring-save' between the BEG and END
positions.  Otherwise, copy the current line.

(fn &optional BEG END)" t)
(autoload 'jp-simple-kill-region "jp-simple" "\
Do `kill-region' when the region is active, else `kill-ring-save' symbol at point.

(fn &optional BEG END)" t)
(autoload 'jp-simple-duplicate-line-or-region "jp-simple" "\
Duplicate the current line or active region." t)
(autoload 'jp-simple-yank-replace-line-or-region "jp-simple" "\
Replace line or region with latest kill.
This command can then be followed by the standard
`yank-pop' (default is bound to \\[yank-pop])." t)
(autoload 'jp-simple-multi-line-below "jp-simple" "\
Move half a screen below." t)
(autoload 'jp-simple-multi-line-above "jp-simple" "\
Move half a screen above." t)
(autoload 'jp-simple-kill-line-backward "jp-simple" "\
Kill from point to the beginning of the line." t)
(autoload 'jp-simple-copy-line-forward "jp-simple" "\
Copy from point to the end of the Nth line.
Without numeric prefix argument N, operate on the current line.

(fn N)" t)
(autoload 'jp-simple-copy-line-backward "jp-simple" "\
Copy from point to the beginning of the Nth line.
Without numeric prefix argument N, operate on the current line.

(fn N)" t)
(autoload 'jp-simple-delete-line "jp-simple" "\
Delete (not kill) from point to the end of the line." t)
(autoload 'jp-simple-delete-line-backward "jp-simple" "\
Delete (not kill) from point to the beginning of the line." t)
(autoload 'jp-simple-auto-fill-visual-line-mode "jp-simple" "\
Enable `visual-line-mode' and disable `auto-fill-mode' in the current buffer.

This is a minor mode.  If called interactively, toggle the
`Jp-Simple-Auto-Fill-Visual-Line mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `jp-simple-auto-fill-visual-line-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'jp-simple-insert-date "jp-simple" "\
Insert the current date as `jp-simple-date-specifier'.

With optional prefix ARG (\\[universal-argument]) also append the
current time understood as `jp-simple-time-specifier'.

When region is active, delete the highlighted text and replace it
with the specified date.

(fn &optional ARG)" t)
(autoload 'jp-simple-escape-url-line "jp-simple" "\
Escape all URLs or email addresses on the current line.
When called from Lisp CHAR is a buffer position to operate from
until the end of the line.  In interactive use, CHAR corresponds
to `line-beginning-position'.

(fn CHAR)" t)
(autoload 'jp-simple-escape-url-region "jp-simple" "\
Apply `jp-simple-escape-url-line' on region lines between BEG and END.

(fn &optional BEG END)" t)
(autoload 'jp-simple-escape-url-dwim "jp-simple" "\
Escape URL on the current line or lines implied by the active region.
Call the commands `jp-simple-escape-url-line' and
`jp-simple-escape-url-region' ." t)
(autoload 'jp-simple-zap-to-char-backward "jp-simple" "\
Backward `zap-to-char' for CHAR.
Optional ARG is a numeric prefix to match ARGth occurance of
CHAR.

(fn CHAR &optional ARG)" t)
(autoload 'jp-simple-flush-and-diff "jp-simple" "\
Call `flush-lines' for REGEXP and produce diff if file is modified.
When region is active, operate between the region boundaries
demarcated by BEG and END.

(fn REGEXP BEG END)" t)
 (autoload 'jp-simple-transpose-lines "jp-simple")
 (autoload 'jp-simple-transpose-paragraphs "jp-simple")
 (autoload 'jp-simple-transpose-sentences "jp-simple")
 (autoload 'jp-simple-transpose-sexps "jp-simple")
 (autoload 'jp-simple-transpose-words "jp-simple")
(autoload 'jp-simple-transpose-chars "jp-simple" "\
Always transposes the two characters before point.
There is no dragging the character forward.  This is the
behaviour of `transpose-chars' when point is at the end of the
line." t)
(autoload 'jp-simple-unfill-region-or-paragraph "jp-simple" "\
Unfill current paragraph or the active region." t)
(autoload 'jp-simple-other-window "jp-simple" "\
Wrapper for `other-window' and `next-multiframe-window'.
If there is only one window and multiple frames, call
`next-multiframe-window'.  Otherwise, call `other-window'." t)
(autoload 'jp-simple-narrow-visible-window "jp-simple" "\
Narrow buffer to wisible window area.
Also check `jp-simple-narrow-dwim'." t)
(autoload 'jp-simple-narrow-dwim "jp-simple" "\
Do-what-I-mean narrowing.
If region is active, narrow the buffer to the region's
boundaries.

If pages are defined by virtue of `jp-common-page-p', narrow to
the current page boundaries.

If no region is active and no pages exist, narrow to the visible
portion of the window.

If narrowing is in effect, widen the view." t)
(autoload 'jp-simple-forward-page-dwim "jp-simple" "\
Move to next or COUNTth page forward.
If buffer is narrowed to the page, keep the effect while
performing the motion.  Always move point to the beginning of the
narrowed page.

(fn &optional COUNT)" t)
(autoload 'jp-simple-backward-page-dwim "jp-simple" "\
Move to previous or COUNTth page backward.
If buffer is narrowed to the page, keep the effect while
performing the motion.  Always move point to the beginning of the
narrowed page.

(fn &optional COUNT)" t)
(autoload 'jp-simple-delete-page-delimiters "jp-simple" "\
Delete lines with just page delimiters in the current buffer.
When region is active, only operate on the region between BEG and
END, representing the point and mark.

(fn &optional BEG END)" t)
(autoload 'jp-simple-narrow-to-cloned-buffer "jp-simple" "\
Narrow to defun in cloned buffer.
Name the buffer after the defun's symbol." t)
(autoload 'jp-simple-display-unsaved-buffers "jp-simple" "\
Produce buffer menu listing unsaved file-visiting buffers." t)
(autoload 'jp-simple-copy-current-buffer-name "jp-simple" "\
Add the current buffer's name to the `kill-ring'." t)
(function-put 'jp-simple-copy-current-buffer-name 'interactive-only 't)
(autoload 'jp-simple-copy-current-buffer-file "jp-simple" "\
Add the current buffer's file path to the `kill-ring'." t)
(function-put 'jp-simple-copy-current-buffer-file 'interactive-only 't)
(autoload 'jp-simple-kill-buffer "jp-simple" "\
Kill current BUFFER without confirmation.
When called interactively, prompt for BUFFER.

(fn BUFFER)" t)
(autoload 'jp-simple-kill-buffer-dwim "jp-simple" "\
Kill current buffer.
With optional prefix ARG (\\[universal-argument]) delete the
buffer's window as well.  Kill the window regardless of ARG if it
satisfies `jp-common-window-small-p' and it has no previous
buffers in its history.

(fn &optional ARG)" t)
(autoload 'jp-simple-copy-current-path "jp-simple" "\
Copy the current absolute path.
If in a file-visiting buffer, copy the `buffer-file-name'.  Else copy
the `default-directory'." t)
(function-put 'jp-simple-copy-current-path 'interactive-only 't)
(autoload 'jp-simple-rename-file-and-buffer "jp-simple" "\
Apply NAME to current file and rename its buffer.
Do not try to make a new directory or anything fancy.

(fn NAME)" t)
(autoload 'jp-simple-buffers-major-mode "jp-simple" "\
Select BUFFER matching the current one's major mode." t)
(autoload 'jp-simple-buffers-vc-root "jp-simple" "\
Select buffer matching the current one's VC root." t)
(autoload 'jp-simple-swap-window-buffers "jp-simple" "\
Swap states of live buffers.
With two windows, transpose their buffers.  With more windows,
perform a clockwise rotation.  Do not alter the window layout.
Just move the buffers around.

With COUNTER as a prefix argument, do the rotation
counter-clockwise.

(fn COUNTER)" t)
(autoload 'jp-simple-list-accessible-colors "jp-simple" "\
Return buffer with list of accessible `defined-colors'.
VARIANT is either `dark' or `light'.

(fn VARIANT)" t)
(autoload 'jp-simple-update-some-or-all-of-my-package-repositories "jp-simple" "\
Prompt for PACKAGES among `jp-emacs-my-packages' to pull or clone.
With a universal prefix argument for ALL-PACKAGES, do not prompt for packages and
update them all instead.

(fn PACKAGES &optional ALL-PACKAGES)" t)
(register-definition-prefixes "jp-simple" '("jp-"))


;;; Generated autoloads from jp-spell.el

(autoload 'jp-spell-change-dictionary "jp-spell" "\
Select a DICTIONARY from `jp-spell-dictionaries'.

(fn DICTIONARY)" t)
(autoload 'jp-spell-spell-dwim "jp-spell" "\
Spell check between BEG END, current word, or select a dictionary.

Use `flyspell-region' on the active region and deactivate the
mark.

With point over a word and no active region invoke `ispell-word'.

Else call `jp-spell-change-dictionary'.

(fn BEG END)" t)
(register-definition-prefixes "jp-spell" '("jp-spell-"))


;;; Generated autoloads from jp-vertico.el

(register-definition-prefixes "jp-vertico" '("jp-vertico-"))


;;; Generated autoloads from jp-window.el

 (autoload 'jp-window-shell "jp-window")
 (autoload 'jp-window-meeting "jp-window")
 (autoload 'jp-window-popup-org-capture "jp-window")
 (autoload 'jp-window-popup-tmr "jp-window")
 (autoload 'jp-window-popup-jp-project-switch "jp-window")
(register-definition-prefixes "jp-window" '("jp-window-"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
