themes:
  - name: "miasma"
    colors:
      - "#1c1c1c"
      - "#444444"
      - "#666666"
      - "#c2c2b0"
      - "#eaeaea"
      - "#1f3a5f"
      - "#87CEEB"
      - "#2f361f"
      - "#43492a"
      - "#5f875f"
      - "#685742"
      - "#fd9720"
      - "#b36d43"
      - "#c86448"
      - "#661010"
      - "#d7c483"
