# Unbind omarchy bindindgs
unbind = SUPER, RETURN
unbind = SUPER SHIFT, RETURN
unbind = SUPER SHIFT, R
unbind = SUPER, G
unbind = SUPER, P
unbind = SUPER SHIFT, E
unbind = SUPER, W
unbind = SUPER SHIFT, P
unbind = SUPER, code:61
unbind = SUPER SHIFT, A
unbind = SUPER SHIFT, G
unbind = SUPER SHIFT, W
unbind = SUPER SHIFT, T
unbind = SUPER, SPACE
unbind = SUPER, O
unbind = ,PRINT
unbind = SUPER SHIFT, S
unbind = ALT, PRINT
unbind = SUPER SHIFT, BACKSPACESHIFT
unbind = SUPER, V
unbind = SUPER, K
unbind = SUPER, L

# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, E, File manager, exec, uwsm app -- nautilus --new-window
bind = SUPER, E, exec, emacsclient -c -e '(dired "~")'
bindd = SUPER, W, Browser, exec, $browser
bindd = SUPER SHIFT, P, Browser (private), exec, $browser --private
bind = SUPER, q,exec, hyprctl dispatch killactive
bindd = SUPER, SLASH, Editor, exec, emacsclient -c -a ''

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, G, Github, exec, omarchy-launch-webapp "https://github.com/jpachecoxyz"
bindd = SUPER SHIFT, T, Telegram, exec, omarchy-launch-or-focus-webapp Telegram "https://web.telegram.org/k/"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp Youtube "https://youtube.com"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
bindd = SUPER, O, Omarchy menu, exec, omarchy-launch-walker
bindd = ,PRINT , Screenshot Full, exec, omarchy capture screenshot fullscreen

bindd = SUPER SHIFT, S, Screenshot, exec, omarchy capture screenshot region
bindd = SUPER SHIFT, Print, Screenshot, exec, omarchy menu capture

# bindd = SUPER SHIFT, R, Screenrecording, exec, screencast
bindd = SUPER SHIFT, R, Screenrecording, exec, omarchy-menu screenrecord

# Terminal scratchpad
# bindd = SUPER SHIFT, Return, Scratchpad, exec, pypr toggle term

# Clipboard
bindd = SUPER, V, Clipboard manager, exec, omarchy-launch-walker -m clipboard

# [[ Window management ]]
# Move focus with mainMod + j or k, yes vi keys...
bind = SUPER, J, cyclenext
bind = SUPER, K, cyclenext, prev

# Swap windows
bind = SUPER SHIFT, J, swapnext, next
bind = SUPER SHIFT, K, swapnext, prev

# Resize windows / Move windows
binde = SUPER , L, resizeactive, 40 0
binde = SUPER , h, resizeactive, -40 0
binde = SUPER , right, moveactive, 50 0
binde = SUPER , left, moveactive, -50 0
binde = SUPER , down, moveactive, 0 50
binde = SUPER , up, moveactive, 0 -50

bindd = SUPER SHIFT, L, Hyprlock, exec, hyprlock

# Floating windows
bind = SUPER, SPACE, togglefloating
bind = SUPER, SPACE, resizeactive, exact 1260 600
bind = SUPER, SPACE, centerwindow
bind = CTRL, SPACE, togglespecialworkspace, magic
bind = CTRL, SPACE, movetoworkspace, +0
bind = CTRL, SPACE, togglespecialworkspace, magic
bind = CTRL, SPACE, movetoworkspace, special:magic
bind = CTRL, SPACE, togglespecialworkspace, magic

# Special Workspaces.
# bind = CTRL, SPACE, togglespecialworkspace
# bind = SUPER SHIFT, A, togglespecialworkspace, chatgpt
bind = SUPER SHIFT, A, togglespecialworkspace, gemini
bind = SUPER SHIFT, W, togglespecialworkspace, whatsapp
bind = SUPER SHIFT, RETURN, togglespecialworkspace, scratchpad
