[pyprland]
plugins = [
  "scratchpads",
  "shortcuts_menu",
  "expose",
  "layout_center"
]

# [scratchpads.term]
# animation = "fromTop"
# command = "foot -a scratchpad"
# lazy = true
# size = "75% 60%"
# max_size = "1920px 100%"
# margin = 50

[scratchpads.term]
animation = "fromBottom"
command = "foot -a scratchpad -T Scratchpad"
lazy = true
size = "75% 50%"
max_size = "1920px 100%"
position = "15% 25%"
margin = 70

[scratchpads.tomb]
animation = "fromBottom"
command = "foot -a scratchpad -e tmount.sh"
lazy = true
size = "50% 40%"
max_size = "1920px 100%"
position = "25% 55%"
margin = 50

[scratchpads.emacs]
animation = "fromTop"
command = "emacs"
class = "Emacs"
lazy = true

# Shorcuts_menu 
[shortcuts_menu]
engine = "fuzzel"
# parameters = "-p '[prompt] 🍰 ' -dmenu -matching fuzzy -i"
command_start = "💀 "

[shortcuts_menu.entries]
"tombs" = "pypr toggle tomb && hyprctl dispatch bringactivetotop && $updateWaybar"
"mount" = "hypr-scratchpads fzmount"
"clipboard" = [
    {name="entry", command="cliphist list", filter="s/\t.*//"},
    "cliphist decode '[entry]' | wl-copy"
]

# layout_center.
[layout_center]
style = ["opacity 1", "bordercolor rgb(FFFF00)"]
margin = 0
